### ISSUE TITLE
Add Persian labguage and Rial currency

### ISSUE THREAD

**Issue by neesti** [Numbertext/libnumbertext#100]
Hello. 

Please support Persian (Farsi) language and Rial currency in next version of this Add-on. 

Thank you so much.

**Comment by neesti** [comment]
Hello. 

Would you please review this pull request:

https://github.com/Numbertext/libnumbertext/pull/101

Thank you.

**Comment by laszlonemeth** [comment]
Hello, Neesti,

Thanks for your request! I'll check the module soon, and report the result!

Best regards,
László

**Comment by laszlonemeth** [comment]
@amiria703's nice patch has already merged, and it will be released soon.

Thanks for your request again!

Best regards,
László
 
P.S. FYI, Copying the module fa.sor in numbertext folder of the LibreOffice installation, it's possible to use it by the following user-defined number format:

[NatNum12 cardinal]0

or

[NatNum12 IRR]0

But my plan to add NumberText menu items to the number format dialog window.

**Comment by laszlonemeth** [comment]
Hi,

The problem was fixed by @amiria703, integrated with the new v1.0.11 release, integrated with LibreOffice, too.

The result will be visible in LibreOffice 7.5, according to the new number and currency formats of the Calc Cell and Writer Field formatting dialog windows:

https://wiki.documentfoundation.org/ReleaseNotes/7.5#Default_.E2.80.9Cspell_out.E2.80.9D_number_and_currency_formats

I have added only the cardinal number, because I will ask help on l10n mailing list of LibreOffice to check RTL and CTL language support in Calc/Writer.

Many thanks for your bug report!

Best regards,
László
