### ISSUE TITLE
Add feminine for french language

### ISSUE THREAD

**Issue by arena94** [Numbertext/libnumbertext#89]
This is a small and specific change 

ca.sor has in lines 148 to 158 the following sections :

```
== feminine ==

1 una
(.*)	$(f:|$1)

== masculine ==

1 un
(.*)	$1
```

It would be interesting to insert in fr.sor  after line 135 the following sections :

```
== feminine ==

1 une
(.*)	$(f:|$1)

== masculine ==

1 un
(.*)	$1
```

default being masculine ... and modify the == help == section accordingly

thank you for the good work !

p.s. : apparently other latin languages should have this rule (not found in es.sor, found something in it.sor but different from ca.sor ...)

**Comment by laszlonemeth** [comment]
Hi,

The problem was fixed by the previous patch of new v1.0.11 release, integrated with LibreOffice, too.

The result will be visible in LibreOffice 7.5, according to the new number and currency formats of the Calc Cell and Writer Field formatting dialog windows:

https://wiki.documentfoundation.org/ReleaseNotes/7.5#Default_.E2.80.9Cspell_out.E2.80.9D_number_and_currency_formats

Many thanks for your bug report!

Best regards,
László
