### ISSUE TITLE
Translating thousands in french

### ISSUE THREAD

**Issue by arena94** [Numbertext/libnumbertext#90]
Currently, the software translate number 1100 in 'onze cents' but 1200 in 'mille deux cents'

For legal purpose i would like to be able to translate 1100 in 'mille cent'.

as stated by the Académie Française ... 

> Dans l’usage courant, au lieu de mille cent, mille deux cents, etc., on dit plutôt onze cents, douze cents, etc., jusqu’à dix-neuf cents : Onze cents francs, seize cents euros. En revanche, dans la langue écrite, et notamment dans un texte juridique, administratif ou scientifique, on préfèrera les formes : mille cent, mille deux cents, etc. Une somme de mille deux cent cinquante francs. Une superficie de mille cinq cents mètres carrés.

[source](https://www.dictionnaire-academie.fr/article/A9M2155#:~:text=Dans%20l'usage%20courant%2C%20au,cents%20francs%2C%20seize%20cents%20euros.)

is it possible ?

apparently in  fr.sor  there is a special rule lines 45 & 46 for this ...

thank you for your help

**Comment by laszlonemeth** [comment]
Hi,

The problem was solved in the previous patches of the v1.0.10 release, integrated with LibreOffice, too.

The result will be quite visible in LibreOffice 7.5, according to the new number and currency formats of the Calc Cell and Writer Field formatting dialog windows:

https://wiki.documentfoundation.org/ReleaseNotes/7.5#Default_.E2.80.9Cspell_out.E2.80.9D_number_and_currency_formats

Many thanks for your bug report!

Best regards,
László
