### ISSUE TITLE
Wrong text for $0.21 in Russian and Ukrainian

### ISSUE THREAD

**Issue by zeezooz** [Numbertext/libnumbertext#99]
Hi!

The word cents has an incorrect form for the values [2-9]1. It should be the same as for $0.01 (цент) instead of центов/центів.

https://numbertext.github.io/#testimonials
![image](https://user-images.githubusercontent.com/5618861/197546390-304f769b-fba3-4799-8001-e97891c133eb.png)
![image](https://user-images.githubusercontent.com/5618861/197546471-95bb50ff-357b-487c-8538-bd6389a40dc6.png)
![image](https://user-images.githubusercontent.com/5618861/197546528-42cbaeab-e223-4c8c-892f-fa214b362827.png)

LibreOffice extension 1.0.9 (1.0.10 isn't available at extensions.libreoffice.org)
![image](https://user-images.githubusercontent.com/5618861/197547537-b45b494d-58a4-4798-bc19-cebc168cee8e.png)

**Comment by contributorpw** [comment]
There was no such problem before.
![1666618556830](https://user-images.githubusercontent.com/5027939/197538887-36927a85-f31b-480e-b73b-5e85362b3a87.png)

Can you clarify which assembly you are using? How can I replicate this problem?

**Comment by contributorpw** [comment]
OK.

I added a separate definition for decimals greater than 20. But now it seems to me that this whole thing could be simpler. You can still think and do refactoring of all these rules.

**Comment by laszlonemeth** [comment]
Dear Andrew,

Thanks to Alex Ivanov, this problem was fixed in libnumbertext. I'm going to update the integrated libnumbertext of LibreOffice, so using NatNum12 number format, it will be possible to access to the fix immediately, without installing the NumberText extension. 

Note: I started to add selectable NUMBERTEXT and MONEYTEXT number formats to Cell formatting dialog window, too:

https://gerrit.libreoffice.org/c/core/+/141994 tdf#115007 add NatNum12 number format list items, fix title case
https://gerrit.libreoffice.org/c/core/+/142126 tdf#115007  i18npool: add NatNum12 formats to locale

Many thanks for your bug report!

Best regards,
László
